parameters:
    sip.translation.listener.class: SIP\TranslationBundle\EventListener\TranslationListener
    sip.translation.form.type.translation.class: SIP\TranslationBundle\Form\Type\TranslationType

services:
    sip.translation.listener:
        class: %sip.translation.listener.class%
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }
            - { name: doctrine.event_listener, event: postGenerateSchema }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postFlush }
        arguments: [@service_container]

    sip.translation.form.type.translation:
        class: %sip.translation.form.type.translation.class%
        arguments: [@sip.translation.listener, @doctrine.orm.entity_manager]
        tags:
            - { name: form.type, alias: translation }